import React from 'react';
import { Ban, ShieldAlert, Lock } from 'lucide-react';

const AccessDenied: React.FC = () => {
  const rayId = Math.random().toString(16).substr(2, 16);

  return (
    <div className="min-h-screen bg-[#050505] text-zinc-100 font-sans flex flex-col">
      <header className="border-b border-zinc-900 p-6">
        <div className="max-w-4xl mx-auto flex items-center gap-2 text-red-600 font-bold text-xl tracking-tight">
          <ShieldAlert />
          NAMELESS GUARD
        </div>
      </header>

      <main className="flex-grow flex items-center justify-center p-6">
        <div className="max-w-4xl w-full grid grid-cols-1 md:grid-cols-2 gap-12 items-center">
          
          <div className="space-y-6">
            <h1 className="text-5xl md:text-6xl font-extrabold text-white tracking-tight leading-none">
              Access <br/>
              <span className="text-red-600">Denied</span>
            </h1>
            <p className="text-lg text-zinc-400 font-light">
              The owner of this script has banned your access based on your browser's signature.
            </p>
            
            <div className="bg-red-500/5 border border-red-900/30 rounded-lg p-4 text-sm text-red-200/80 space-y-2">
              <div className="flex items-center gap-2 font-bold text-red-400">
                <Lock size={16} />
                Error 1020
              </div>
              <p>You do not have permission to access this resource.</p>
            </div>
          </div>

          <div className="bg-[#0f0f0f] border border-zinc-800 rounded-2xl p-8 space-y-6 shadow-2xl">
            <div className="flex justify-center mb-4">
              <div className="w-20 h-20 bg-zinc-900 rounded-full flex items-center justify-center border border-zinc-800">
                <Ban className="w-10 h-10 text-zinc-500" />
              </div>
            </div>
            
            <div className="space-y-4 text-sm font-mono text-zinc-500">
              <div className="flex justify-between border-b border-zinc-800 pb-2">
                <span>Your IP:</span>
                <span className="text-zinc-300">192.168.1.x</span>
              </div>
              <div className="flex justify-between border-b border-zinc-800 pb-2">
                <span>Ray ID:</span>
                <span className="text-zinc-300">{rayId}</span>
              </div>
              <div className="flex justify-between border-b border-zinc-800 pb-2">
                <span>Action:</span>
                <span className="text-red-500">Block</span>
              </div>
            </div>

            <div className="pt-2 text-center text-xs text-zinc-600">
              Generated by Nameless Guard Protection
            </div>
          </div>

        </div>
      </main>
    </div>
  );
};

export default AccessDenied;